### ISSUE TITLE
make code of conduct

### ISSUE THREAD

**Issue by Mudrank** [Beat-Rate/Beat-Rate#4]
@RonaldColyar

**Comment by RonaldColyar** [comment]
@Mudrank  I am assigning you this! Can you work on this?

**Comment by Mudrank** [comment]
> @Mudrank  I am assigning you this! Can you work on this? 

Yeah sure 👍

**Comment by Mudrank** [comment]
done! [check it out here](https://github.com/Beat-Rate/Beat-Rate/blob/master/Documentation/code_of_conduct.md)
